### ISSUE TITLE
Add support for italic fonts.

### ISSUE THREAD

**Issue by birobirobiro** [sonidolabs/davinci#2]
I use the Dank Mono font and I really liked its theme and I would like it to support the italic option as well. Check out what it looks like in another theme, [Moonlight](https://marketplace.visualstudio.com/items?itemName=atomiks.moonlight)

`Moonlight`

![image](https://github.com/sonidolabs/davinci/assets/22185823/cc509204-3984-4a87-a9d9-f00fae81f8b2)

`Davinci`

![image](https://github.com/sonidolabs/davinci/assets/22185823/bf333e6e-9ba4-403c-b132-80ec37ceb778)

**Comment by Gabriel3atista** [comment]
We will not currently support italics, as this would require creating many theme variants.
